# Q-Table Learning

In [1]:
import gym
import numpy as np

### Load the environment

In [2]:
env = gym.make('FrozenLake-v0')

[2017-01-31 13:09:16,339] Making new env: FrozenLake-v0


### Implement Q-Table learning algorithm

In [11]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            if rAll == 1.0:
                strr = "Success"
            else:
                strr = "Game over"
            print "Game %d played until step %d: %s, final reward=%s" % (i,j,strr,rAll)
            break
    #jList.append(j)
    rList.append(rAll)

Game 0 played until step 4: Game over, final reward=0.0
Game 1 played until step 3: Game over, final reward=0.0
Game 2 played until step 3: Game over, final reward=0.0
Game 3 played until step 2: Game over, final reward=0.0
Game 4 played until step 4: Game over, final reward=0.0
Game 5 played until step 4: Game over, final reward=0.0
Game 6 played until step 6: Game over, final reward=0.0
Game 7 played until step 4: Game over, final reward=0.0
Game 8 played until step 5: Game over, final reward=0.0
Game 9 played until step 10: Game over, final reward=0.0
Game 10 played until step 2: Game over, final reward=0.0
Game 11 played until step 24: Game over, final reward=0.0
Game 12 played until step 6: Game over, final reward=0.0
Game 13 played until step 4: Game over, final reward=0.0
Game 14 played until step 5: Game over, final reward=0.0
Game 15 played until step 6: Game over, final reward=0.0
Game 16 played until step 21: Game over, final reward=0.0
Game 17 played until step 8: Game over

In [12]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.0215


In [8]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[  3.34267045e-01   1.10723989e-02   1.18387228e-02   9.18157463e-03]
 [  1.29893882e-04   3.03047606e-03   1.28935929e-04   2.21853978e-01]
 [  4.54159988e-01   8.00775132e-03   1.81662658e-03   5.65991466e-03]
 [  5.98026215e-03   3.61134687e-05   6.04508012e-03   6.00508418e-03]
 [  2.46109910e-01   1.95557783e-03   1.51697240e-03   1.77700092e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.28074920e-02   1.27268552e-04   2.07309738e-04   1.02952800e-08]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.83132310e-03   1.00386276e-02   2.73805321e-03   4.70163831e-01]
 [  0.00000000e+00   7.49327463e-01   0.00000000e+00   8.47056945e-04]
 [  3.59886364e-01   0.00000000e+00   5.11545217e-04   3.88084905e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   3.00984580e-03   9.22051696e-01   0